-- AlterTable
ALTER TABLE `MosqueUser` MODIFY `version` INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `mosques` MODIFY `version` INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `roles` ADD COLUMN `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `deleted_at` DATETIME(3) NULL,
    ADD COLUMN `updated_at` DATETIME(3) NULL,
    ADD COLUMN `version` INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `user_role` MODIFY `version` INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `users` MODIFY `version` INTEGER NOT NULL DEFAULT 0;
